# Deploy Job Template
# Deployment job for Azure Function App

parameters:
  - name: environment
    type: string
    displayName: 'Environment (dev/test/prod)'
  
  - name: azureSubscription
    type: string
    displayName: 'Azure service connection'
  
  - name: functionAppName
    type: string
    displayName: 'Function App name'
  
  - name: vmImage
    type: string
    default: 'ubuntu-latest'
    displayName: 'VM image for deployment agent'
  
  - name: dependsOn
    type: object
    default: []
    displayName: 'Job dependencies'
  
  - name: workingDirectory
    type: string
    default: ''
    displayName: 'Working directory (optional)'
  
  - name: jobName
    type: string
    default: 'Deploy'
    displayName: 'Job name'

jobs:
  - deployment: ${{ parameters.jobName }}
    displayName: 'Deploy to ${{ parameters.environment }}'
    environment: ${{ parameters.environment }}
    pool:
      vmImage: ${{ parameters.vmImage }}
    dependsOn: ${{ parameters.dependsOn }}
    
    strategy:
      runOnce:
        deploy:
          steps:
            # Download build artifacts
            - download: current
              artifact: drop
              displayName: 'Download build artifacts'

            # Deploy to Function App
            - template: ../steps/deploy-function-app.yml
              parameters:
                azureSubscription: ${{ parameters.azureSubscription }}
                functionAppName: ${{ parameters.functionAppName }}
                package: '$(Pipeline.Workspace)/drop/**'
                workingDirectory: ${{ parameters.workingDirectory }}
