# CI Stage Template
# Continuous Integration stage with build and test

parameters:
  - name: nodeVersion
    type: string
    default: '22.x'
    displayName: 'Node.js version'
  
  - name: workingDirectory
    type: string
    default: ''
    displayName: 'Working directory (optional)'
  
  - name: stageName
    type: string
    default: 'CI'
    displayName: 'Stage name'
  
  - name: displayName
    type: string
    default: 'Build and Test'
    displayName: 'Stage display name'
  
  - name: vmImage
    type: string
    default: 'ubuntu-latest'
    displayName: 'VM image for build agent'
  
  - name: runAutomatedTests
    type: boolean
    default: false
    displayName: 'Run automated tests'
  
  - name: testRepoUrl
    type: string
    default: ''
    displayName: 'Test repository URL (if running automated tests)'

stages:
  - stage: ${{ parameters.stageName }}
    displayName: ${{ parameters.displayName }}
    jobs:
      - template: ../jobs/build-and-test.yml
        parameters:
          nodeVersion: ${{ parameters.nodeVersion }}
          workingDirectory: ${{ parameters.workingDirectory }}
          vmImage: ${{ parameters.vmImage }}
          jobName: 'BuildAndTest'
          displayName: 'Build and Test'
          runAutomatedTests: ${{ parameters.runAutomatedTests }}
          testRepoUrl: ${{ parameters.testRepoUrl }}
