# Infrastructure Deployment Example
# Deploy infrastructure for a single service
# Run this once to create your Azure resources

name: Deploy Infrastructure

trigger: none # Manual trigger only

parameters:
  - name: environment
    displayName: 'Environment to deploy'
    type: string
    default: 'dev'
    values:
      - dev
      - test
      - prod
  
  - name: serviceName
    displayName: 'Service name'
    type: string
    default: 'myservice'

variables:
  - name: location
    value: 'swedencentral'
  - name: azureSubscription
    value: 'Azure-Connection'
  
  # Variable groups for secrets
  - group: 'qops-secrets-${{ parameters.environment }}'

# Reference templates repo
resources:
  repositories:
    - repository: templates
      type: git
      name: qops-hub-kit
      ref: refs/heads/main

stages:
  - stage: ValidateInfrastructure
    displayName: 'Validate Bicep Templates'
    jobs:
      - job: Validate
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - checkout: templates

          - task: AzureCLI@2
            displayName: 'Validate Bicep template'
            inputs:
              azureSubscription: $(azureSubscription)
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                echo "Validating Bicep template for ${{ parameters.serviceName }}"
                az bicep build --file infra/service.bicep
                echo "✅ Bicep template is valid"

  - stage: DeployInfrastructure
    displayName: 'Deploy Infrastructure to ${{ upper(parameters.environment) }}'
    dependsOn: ValidateInfrastructure
    jobs:
      - job: Deploy
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - checkout: templates

          - task: AzureCLI@2
            displayName: 'Deploy Bicep template'
            inputs:
              azureSubscription: $(azureSubscription)
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                echo "Deploying ${{ parameters.serviceName }} infrastructure to ${{ parameters.environment }}"
                
                # Deploy the service infrastructure
                DEPLOYMENT_NAME="deploy-${{ parameters.serviceName }}-$(Build.BuildId)"
                
                az deployment sub create \
                  --name $DEPLOYMENT_NAME \
                  --location $(location) \
                  --template-file infra/service.bicep \
                  --parameters environment=${{ parameters.environment }} \
                  --parameters serviceName=${{ parameters.serviceName }} \
                  --parameters location=$(location) \
                  --parameters jwtSecret="$(JWT_SECRET)" \
                
                echo ""
                echo "✅ Infrastructure deployment complete!"
                echo ""
                
                # Get deployment outputs
                echo "📋 Deployment outputs:"
                FUNCTION_APP_NAME=$(az deployment sub show \
                  --name $DEPLOYMENT_NAME \
                  --query properties.outputs.functionAppName.value -o tsv)
                
                FUNCTION_APP_URL=$(az deployment sub show \
                  --name $DEPLOYMENT_NAME \
                  --query properties.outputs.functionAppUrl.value -o tsv)
                
                RESOURCE_GROUP=$(az deployment sub show \
                  --name $DEPLOYMENT_NAME \
                  --query properties.outputs.resourceGroupName.value -o tsv)
                
                echo "  Resource Group: $RESOURCE_GROUP"
                echo "  Function App: $FUNCTION_APP_NAME"
                echo "  Function App URL: $FUNCTION_APP_URL"
                echo ""
                echo "💡 Add these to your service pipeline variables:"
                echo "  functionAppName${{ parameters.environment }}: $FUNCTION_APP_NAME"
